# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cloudDrive.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63loudDrive.proto\"*\n\x13\x63reateFolderRequest\x12\x13\n\x0b\x66older_name\x18\x01 \x01(\t\"M\n\x11updateFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_size\x18\x02 \x01(\x05\x12\x12\n\nfile_bytes\x18\x03 \x01(\x0c\"&\n\x11\x64\x65leteFileRequest\x12\x11\n\tfile_name\x18\x01 \x01(\t\"\x1c\n\x08Response\x12\x10\n\x08response\x18\x01 \x01(\t2\xa3\x01\n\ncloudDrive\x12\x37\n\x12\x63reateBackupFolder\x12\x14.createFolderRequest\x1a\t.Response\"\x00\x12-\n\nuploadFile\x12\x12.updateFileRequest\x1a\t.Response\"\x00\x12-\n\ndeleteFile\x12\x12.deleteFileRequest\x1a\t.Response\"\x00\x62\x06proto3')



_CREATEFOLDERREQUEST = DESCRIPTOR.message_types_by_name['createFolderRequest']
_UPDATEFILEREQUEST = DESCRIPTOR.message_types_by_name['updateFileRequest']
_DELETEFILEREQUEST = DESCRIPTOR.message_types_by_name['deleteFileRequest']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
createFolderRequest = _reflection.GeneratedProtocolMessageType('createFolderRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEFOLDERREQUEST,
  '__module__' : 'cloudDrive_pb2'
  # @@protoc_insertion_point(class_scope:createFolderRequest)
  })
_sym_db.RegisterMessage(createFolderRequest)

updateFileRequest = _reflection.GeneratedProtocolMessageType('updateFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEFILEREQUEST,
  '__module__' : 'cloudDrive_pb2'
  # @@protoc_insertion_point(class_scope:updateFileRequest)
  })
_sym_db.RegisterMessage(updateFileRequest)

deleteFileRequest = _reflection.GeneratedProtocolMessageType('deleteFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEFILEREQUEST,
  '__module__' : 'cloudDrive_pb2'
  # @@protoc_insertion_point(class_scope:deleteFileRequest)
  })
_sym_db.RegisterMessage(deleteFileRequest)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'cloudDrive_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_CLOUDDRIVE = DESCRIPTOR.services_by_name['cloudDrive']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATEFOLDERREQUEST._serialized_start=20
  _CREATEFOLDERREQUEST._serialized_end=62
  _UPDATEFILEREQUEST._serialized_start=64
  _UPDATEFILEREQUEST._serialized_end=141
  _DELETEFILEREQUEST._serialized_start=143
  _DELETEFILEREQUEST._serialized_end=181
  _RESPONSE._serialized_start=183
  _RESPONSE._serialized_end=211
  _CLOUDDRIVE._serialized_start=214
  _CLOUDDRIVE._serialized_end=377
# @@protoc_insertion_point(module_scope)
