# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import cloudDrive_pb2 as cloudDrive__pb2


class cloudDriveStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createBackupFolder = channel.unary_unary(
                '/cloudDrive/createBackupFolder',
                request_serializer=cloudDrive__pb2.createFolderRequest.SerializeToString,
                response_deserializer=cloudDrive__pb2.Response.FromString,
                )
        self.uploadFile = channel.unary_unary(
                '/cloudDrive/uploadFile',
                request_serializer=cloudDrive__pb2.updateFileRequest.SerializeToString,
                response_deserializer=cloudDrive__pb2.Response.FromString,
                )
        self.deleteFile = channel.unary_unary(
                '/cloudDrive/deleteFile',
                request_serializer=cloudDrive__pb2.deleteFileRequest.SerializeToString,
                response_deserializer=cloudDrive__pb2.Response.FromString,
                )


class cloudDriveServicer(object):
    """Missing associated documentation comment in .proto file."""

    def createBackupFolder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_cloudDriveServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createBackupFolder': grpc.unary_unary_rpc_method_handler(
                    servicer.createBackupFolder,
                    request_deserializer=cloudDrive__pb2.createFolderRequest.FromString,
                    response_serializer=cloudDrive__pb2.Response.SerializeToString,
            ),
            'uploadFile': grpc.unary_unary_rpc_method_handler(
                    servicer.uploadFile,
                    request_deserializer=cloudDrive__pb2.updateFileRequest.FromString,
                    response_serializer=cloudDrive__pb2.Response.SerializeToString,
            ),
            'deleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteFile,
                    request_deserializer=cloudDrive__pb2.deleteFileRequest.FromString,
                    response_serializer=cloudDrive__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloudDrive', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class cloudDrive(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def createBackupFolder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudDrive/createBackupFolder',
            cloudDrive__pb2.createFolderRequest.SerializeToString,
            cloudDrive__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def uploadFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudDrive/uploadFile',
            cloudDrive__pb2.updateFileRequest.SerializeToString,
            cloudDrive__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloudDrive/deleteFile',
            cloudDrive__pb2.deleteFileRequest.SerializeToString,
            cloudDrive__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
